POST http://127.0.0.1:8000/api/login_check
Content-Type: application/json

{"username":"test_user","password":"test_password"}

###

# curl -X POST -H "Content-Type: application/json" http://127.0.0.1:8000/api/login_check -d '{"username":"test_user","password":"test_password"}'