GET http://127.0.0.1:8000/api/league/8
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE1MzI4MTgxOTgsImV4cCI6MTUzMjgyMTc5OCwicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoidGVzdF91c2VyIn0.GqBlYYvkCQlPLKlWyG1GlsDANRFLhOuQAHW725rw0H4y8mt8ICHbqnvheJOzDVpxekam8dly3F1PMvlQZvgyY2i7JyRxXKum-oItwRoTqvEiTQ3IvBlAS3TlLdhSDLHs0kkMk7KcslRmL1nNxPt4ZO9SynExoi2EpBIDtheLBDiJy_cO1hOb31obtIdWEgAr09stGBPsfxGSFEq4CDhhdiOknjQ98CYsQXH-tC3IrpOg9JamYEfryzy3AEeO110_7gFwkVFTpELKsvM4GOh86-zq3Buq19llAmmtuGXqGOH8j_Cvyv5WvebX09B4zBkpH1L9oyrKTGxc2APW-WCexjxbF8KAaYvepb4CAmfMnqUeilW7L9ehO9RE0TMbbQJppRJpzfuiJDvB2_2CK4YJ0S-YkUbl1oJOSS2l8LPSguHgE_ubUqxlyJfjLb3PWs5DuxhgQCoxnvBVgoITGHnydyenrt1x6EcxzPrCmzvZh_ruWIGwzaHl6DaILQfMNu9drvYF5eh2QQsoFhZQe6Ymxhs1z13L4IvXPqJJKyYU0d7L2Tl82Hw-vugLgpEtg12x4kzb0UfPsv5tLnt4ljykfLg9d9ewSsN_fEq3c2impXAHYHqIfivYL5wuxzEkTAVCE9HEVaazHPT2nZMia3OSoINis-PpomPhzmBB77da6oE
Accept: application/json

###