POST http://127.0.0.1:8000/api/team
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE1MzI4Nzk3MTEsImV4cCI6MTUzMjkxNTcxMSwicm9sZXMiOlsiSVNfQVVUSEVOVElDQVRFRF9GVUxMWSJdLCJ1c2VybmFtZSI6InRlc3RfdXNlciJ9.u9JoAodW2gVyCEM1x_TV1FPCctJVi89s_x49sm0Z3toBzEp8ogdRsKVJyOR2H4UUZRydLKt8Y7syXFNVTrfMAU60o4UjuiMuIBMywcwNwMbW3Yx5zhV9AHrD4CRWkaXV6pLqZtjlPSFmew9pjZCaATlo_r5GQCvGVB_iQ3uCLtIcO-R_fOPQJ0WOhPK8qIw-Ob25QE0OkM2fSdzV3hNV7Qq1BD_siBZhAB5G_9oPgu_mvXlyoFVNAT6PN7NNEQ4V47dYVh8T9qoQ-fvLALRapuvUne4ZomwdJ4onuEeb2wTL6arxnodXiIGChPqLqjx6T1ekj4sMXYm7yDJJH-AmCE1qtHFNDmFzySZf53G2h2qIkLtwG4loP20qWz6p1tJpMPmiyRg7hpDU3HpV1ByGZm2qDceGhYgpOFLylgXhDUeCN3thFC9vzUHF9TBs9LvuyO5HzQKURV5ynWQZkxV-iEfmdJ_x5-W1f7ELRfJQItJyxHZk_PiW26pQd_93EN-5tvr8QWTFSIZnxuqAWTOIibVVctZutqeAnNcssG4z3A2MccRhnd_v_IFoqnx-ux10dRJ6cWhYooknIsjUQ1MQtUNPhFJVcp4xQABtKhsKGt-W0snv8o7Mq_pRUaKLvK4lvVL-xgVIAfHJbOhXyC5PdgReT_V_asCotF_NFjwzSwA
Content-Type: application/json

{
	"name": "Test name 3",
	"strips": ["red", "yellow"],
	"league_id": 7
}


###