POST http://127.0.0.1:8000/api/team
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE1MzI4MTQwMjQsImV4cCI6MTUzMjgxNzYyNCwicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoidGVzdF91c2VyIn0.JKuXXoTGF3lDldFhAydBEOo9mY6U4mO8u6qMjFPb4jjNibqyEkdxkV7ZfHBQ0TUCg1ihPQRQH1rybaRJUIOblY7dqFmX5wD06At6WyMiZwTgOfp4Gkty4ZUh_VjyHkqJGSf8Odl_RTALdfKC4HNauburGW0E2e5aMxEBofhgS015_bvrRn5NEJoyP-6JYolfSJkFaAgV7TvBV_csirgyc6GgCeOEGbZqr1n0oX73V285jWFPYbVPrl3s0SqIh_USq53Fu79vmWToKnLXq0vw3gfS0Rf3jg0P_Lt4C05IV6sL0sCjgq09XpdzLodVyCmd4MeaW-2lLhI5SEzkPELMCEv-V_ZrS78lb0Mah1H2kijkfWX4zqlE-7TrprwW594Hoq483yQcDFP9qKVZsj4ryHy4rXbfDkbiOsocnNWjnaL788Ul00O-JvCCaxGk4zw-QeCLuuELm8F--54PfkdExq4kK1Prz7FV73VSfjWvKdcX0JoeCT50xHnph4_vLCEKRJob2vwcEDdA8cI-BhqYRc-1EVwx1XCpPRQrkTAM31HlFp93xgFuo0PLdHc2y2RyCJsOXp2if-tXg4KZH29d3rXEu4hyMMPy-K2oAceXitXleG59dvQqHflayV7KHkuSRwxQUH1DY52s0rKIVh-b2zLLRo8YH9ElDEOMf75D0Pk
Content-Type: application/json

{
	"name": "Test name 3",
	"strips": ["red", "yellow"],
	"league_id": 7
}


###