POST http://127.0.0.1:8000/api/team
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE1MzI5MDA5MzIsImV4cCI6MTUzMjkwNDUzMiwicm9sZXMiOlsiSVNfQVVUSEVOVElDQVRFRF9GVUxMWSJdLCJ1c2VybmFtZSI6InRlc3RfdXNlciJ9.Rj-4T_PsPMoI4QGoJZEh16CIbFfDXruaJtr8RfyqtSQiZw-RlP-wSlbr_FMvmH6tLIgTiUO6cSj2I9BKCQK8x2aZWz3PDeyYAb21Onvv-PkQ9yhay7yA-8TTSzVHiQWtBX0hLwHd8qqWuNVlFMi3MWsZu1RipA627QPiPzLMxscWV395X3cOKkbxTp1SjMUKxIUbT3mypCtQ_dtMSRW-vy9uAi-N4BI1_gU5sow9wdatHoQBetAk3-ml_auZyF3Wjvey2pK9ZPdWEQkVEPs66bfSZQCh9UfNPE9gMTZrgK7ZFw-dhMmwE_fKeWm5Rtd4Avx6601wPzsxoOaR8PtxVhDhipl2pP2lsVSz3TPesOG25Pbh8ossTTJiUcXibs4iCoUd7C-UbudVj7t0YQ7mdtln6Hi3DPyi2V8lPNcixWyRgEueyJNQWRjX_2-S8nmbGjWL-pMJDfxL7ZvS5vYciM7z_65eYCWoMPMTeNN6y3TGHOSItWf2gPBQCyTzLDydYdEYqOQTVypqblTwhM_5pzFMG864LocbAddllJ4g7yCSBatRLQLg_VLoKb7x4fYINxqQ_nL53iHdpAYvlkSsDoFJqT3lOLj-GY73B8VeRwy5LgyrGKCKjtyheD7TtaoStoqExK5e9BE2i-2lr7pbp050H-tLfh8ptdCRa8toeAE
Content-Type: application/json

{
	"name": "Test name 3",
	"strips": ["red", "yellow"],
	"league_id": 1
}


###